import Head from "next/head";
import { useState } from "react";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "ajinkya" });
  const addNameMutation = api.post.addName.useMutation();
  const [name, setName] = useState("");
  const [addedName, setAddedName] = useState("");

  const handleAddName = async () => {
    try {
      const result = await addNameMutation.mutateAsync({ name });
      setAddedName(result.name);
    } catch (error) {
      console.error("Failed to add name:", error);
    }
  };

  return (
    <>
      <Head>
        <title>Moon Ecom</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <p className="text-2xl text-black">
          {hello.data ? hello.data.greeting : "Loading tRPC query..."}
        </p>
        <div className="mt-4">
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Enter name"
            className="border p-2"
          />
          <button onClick={handleAddName} className="ml-2 p-2 bg-blue-500 text-white">
            Add Name
          </button>
        </div>
        {/* {addNameMutation.isLoading && <p>Adding name...</p>} */}
        {addedName && <p>Added Name: {addedName}</p>}
      </div>
    </>
  );
}
