import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Moon Ecom</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
